### ISSUE TITLE
Team Week 4

### ISSUE THREAD

**Issue by AadyaDaita** [B-G101/BASE#6]
# Teacher/Peer Grade: 3/3 for Everyone
**Reasoning**: We think we should get a 3/3 because we completed all the required assignments. On top of that, we also added additional hacks for all the assignments like the Java Backend, Hacks for 2D Arrays, Agile Methodology Diagram. Also, we had comprehensive teaching methods and an organized presentation.

## Agile Methodology
- [x] [Scrum Board](https://github.com/users/B-G101/projects/1) Created
- [x] [Issues](https://github.com/B-G101/BASE/issues) Created
- [x] [Team Agile Methodology Diagram](https://b-g101.github.io/BASE/)

![Image](https://user-images.githubusercontent.com/89221238/191304727-67de75c0-4349-4ed8-9e7e-1b950aa4dd9a.png)

## FRQs
- [x] Bria Gilliam Free Response Question ([2018 FRQ Number 1](https://b-g101.github.io/APCSA-BRIA/jupyter/testprep/2022/09/19/first-frq.html))
- [x] Shreya Ahuja Free Response Question ([2018 FRQ Number 1](https://shreya-ahujaa.github.io/fastpages/fastpages/collegboard/frq/2022/09/19/frq-practice.html))
- [x] [2018 Lesson](https://b-g101.github.io/APCSA-BRIA/markdown/test%20prep/2022/09/21/frq-2018.html)

- [x] Ellie Rozenkrants Free Response Question (put link and frq number)
- [x] Aadya Daita Free Response Question ([2019 FRQ Number 1](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/2022/09/14/cb_frq.html))
- [x] [2019 Lesson
](https://ellierozen.github.io/CSA-Repository/2022/09/19/FRQ.html)

## [Iteration 2D Array](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/2022/09/20/basics_of_2d_array.html)
- [X] Bria Gilliam: [2D Array Assignment with Hacks](https://b-g101.github.io/APCSA-BRIA/jupyter/unit4/2022/09/13/2d-array.html)
- [x] Shreya Ahuja: [2D Array Assignment with Hacks](https://shreya-ahujaa.github.io/fastpages/fastpages/arrays/pbl/2022/09/19/iteration-practice.html)
- [x] Ellie Rozenkrants: 2D Array Assignment with Hacks ([link](https://ellierozen.github.io/CSA-Repository/2022/09/19/Monkeys-on-bed.html))
- [x] Aadya Daita: 2D Array Assignment with Hacks ([link](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/2022/09/20/monkeys.html))

## Java Spring Backend/ThymeLeaf
- [x] Aadya: [Commits](https://github.com/AadyaDaita/apcsa_indiv_repo_tri1/commits/master)
- [x] Bria
![Image](https://user-images.githubusercontent.com/89221238/191186877-913d189f-59dc-4c70-a031-f6c2fe4718f9.png)

## Individual Tickets
- [x] Bria([link](https://github.com/B-G101/APCSA-BRIA/issues/4))
- [x] Aadya ([link](https://github.com/AadyaDaita/apcsa_indiv_repo_tri1/issues/5))
- [x] Shreya ([link](https://github.com/shreya-ahujaa/fastpages/issues/6))
- [x] Ellie ([link](https://github.com/ellierozen/CSA-Repository/issues/16))

**Comment by ProRichyMan** [comment]
# 2.7+/3

- [x] Made a process for scrum teams, with roles and keeping up with tasks
- [x] Frog FRQ 2018 - Like the diagrams, code looks good
- [x] Leap Year FRQ 2019 - find leap years, could possibly use some diagrams to help reinforce knowledge
- [x] Column-wise vs Row-wise printing
- [x] Answering questions on code is good wrap up
- [x] Adding onto the greet function, adds counting of characters, counting of vowels

**Comment by samayass** [comment]
**Score: 2.7+/3**
Did Extra wirh Agile Methodology and Backend
- [ ] Agile Methodology - Explained roles of each team member + made a clear, thorough diagram.
- [ ] FRQ 2018 - Visualized problems with images - Explained code with comments + clear explanation
- [ ] FRQ 2019 - Explained the scoring guidelines + showed how the code met the requirements
- [ ] 2D Arrays - Explained the basics of a 2D Array + showed how to display the outputs vertically and horizontally + completed all the hacks with the monkeys.
- [ ] Backend - Added to greet function + displayed the name variable output + counting characters in the input.

**Comment by sarayu-pr11** [comment]
Agile Methodology
- made a very detailed diagram for the scrum process
- clear method for weekly process

FRQ 2018 Part 1
- explained the solutions with images (makes the solution clearer)
- explained their answers with thoroughness and seemed knowledgeable about what they're explaining

FRQ 2019
- blog post with answers and had clear effort 

2D Arrays
- explained the basics of 2D arrays and connected into the iteration mini-lab

Backend
- worked on the greet function which was functional and looked nice 

The team had a great presentation where each person had equal contributions 
2.7+/3

**Comment by iriisyang** [comment]
2.7+/3
- very clear diagram of scrum process
- good pictures explaining logical process of 2018 frq
- thorough explanation of 2019 frq through code and markdown
- introduction to arrays and how used in monkey poem
- add to the greet file in java project

**Comment by tangalice** [comment]
- very detailed Agile methodology diagram that demonstrates the team scrum process
- useful pictures to help explain the 2018 FRQ answer
- explained the 2019 FRQ answer with code sections and markdown comments 
- short blog post about the basics of a 2D array
- added to the greet function on java website

2.7+/3

**Comment by dontran15** [comment]
- [x] Scrum Process 
 - explanation of roles 
 - individual roles 
 - timeline
- [x] FRQs (2018 & 2019)
 - visualizations of frogs (2018)
 - blog (2019; explanation of requirements)
 - code (explanation of main logic for both)
- [x] Iteration
 - lesson about 2D arrays
 - explained imperative style
 - monkey minilab
- [x] Spring Backend/Thymeleaf (expanded on greet page)

**Comment by icyGS** [comment]
2.7+

- Very detailed with the Scrum board and roles 
- Nice explanation of the FRQs, very in-depth and helped us understand the problem, as well as the approach that's taken to solve
- Explained how 2D arrays work very well and gave demonstrations 
- Gave a helpful FAQ page for 2D arrays
- Played around with backend by making more greeting stuff

**Comment by NicholasRamos5** [comment]
Score: 2.7+/3.0
Extra: backend (greeting) and agile methodology explanation. 
2018 FRQ: Showed diagrams to represent FRQs and thoroughly explained each step and how the code functioned.Went over the different outputs of the boolean.  
Agile Methodology: Went over team roles and provided clear and key information
2019 FRQ: Explained how the code worked step by step. Went over the givens and the purpose of each piece.
2D Array: Defined what is was and described its purpose/use. Explained how they utilized the features of itemization with 2d  arrays. - pointed out key difference of columns vs rows. 
Backend Development: added to the greet function and explained the importance of the methods and user inputs.

**Comment by jm1021** [comment]
Shreya - scrum process described, nice diagram.   Nice process understanding and personalization.
Bria - 2018 frog, illustration built into Notebook.  Description of algo.  Nice side by side illustration.
Shreya - 2018 frog part b, multiple simulation side by side illustrations.  Finish with proportion.
Ellie - 2019 leap year part a, description of algorithm, returns count of days.   part b dayofweek described algo with mod 7. 
Aaadya - 2D array basics.  Two brackets.  Described 0 element access.  Described Horiz vs Vert.   Discussed Monkeys.  Imperative described with good language.
Bria - shared counting characters and counting of vowels in FE/BE scenarios.

Nicely done, lots of teaching extras 3.0 for all.
