### ISSUE TITLE
Week 5 Review Ticket

### ISSUE THREAD

**Issue by B-G101** [B-G101/BASE#8]
## Score Given: 2.7/3
- [x] [JavaScript with Website](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/markdown/2022/09/25/clothing_site.html)
- [x] [Fibonaaci Sequence](https://b-g101.github.io/APCSA-BRIA/jupyter/unit4/2022/09/25/class-running-fibonacci.html)
- [x] [Team Planning](https://b-g101.github.io/BASE/markdown/2022/09/26/wireframes.html)

**Comment by dtsivkovski** [comment]
## Score: 2.7+/3

Comments:
- Very good job presenting the idea as well as the purpose behind it - also included ideas for technicals and features
- Wireframe ideas look very professional and show their idea for the website styling
- Proper use of extends in fibonacci, showing for, while, and recursion loops - missing the super() but not a big deal
- Implemented a javascript dress list - repurposed from Mr. M's code, but also reveal plans to modify it around their website

**Comment by NinjaBreadLord** [comment]
### Score: 2.7+
- Outfit store, nice wireframe, good message presented as well. 
- Inclusion of APIs, Search, login system
- Displays knowledge of extends in classes, while slightly different from Mr. Mort's ideal code I think its good
- No super();
- Nice javascript table implemented, relates to the project idea as well

**Comment by jm1021** [comment]
Shreya - Clothing shopping.  Fashion.  Using a lot of API and Pixel finder.  Lots of searching.   Alerts.

Bria/Ellie - Fibo  did not do extends.  Worked on loop in independent print.  Talked about recursive.    Has some learning and review to perform.

Aadya/Shreya - Quicly reviewed FIbo, closer to requirements.  Javascript adapted to project.    Talked about future with javascript and pages.

2.7 for all
