### ISSUE TITLE
Week 6 - Project Approval

### ISSUE THREAD

**Issue by shreya-ahujaa** [B-G101/BASE#9]
## Score from Teacher: 2.8/3

| Name  | Issue | Score |
| ------------- | ------------- | ---|
| Aadya Daita  | [Issue](https://github.com/AadyaDaita/apcsa_indiv_repo_tri1/issues/7)  | 2.7+/3 |
| Bria Gilliam | [Issue](https://github.com/B-G101/APCSA-BRIA/issues/6) | 2.7+/3 |
| Shreya Ahuja | [Issue](https://github.com/shreya-ahujaa/fastpages/issues/8) | 2.7+/3|
| Ellie Rozenkrants | [Issue ](https://github.com/ellierozen/CSA-Repository/issues/18) | 2.7+/3 |

**Comment by jm1021** [comment]
2.8 for all
Ellie - Clothing project with visuals.  Most bought and least bought dress concept.  Style, database and api usage and search.  Wish list, notification.  
Shreya - api store and category, work shown and how she is solving problem
Bria - shared adaptation using characters, divided height by 2.  good adaptation ascii. 
Aadya - share RGB scaled
